# Generated by Django 4.1.4 on 2023-03-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('resi_add', models.CharField(max_length=150)),
                ('office_add', models.CharField(max_length=150)),
                ('office_contact', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=10)),
            ],
        ),
    ]
